[theme]
primaryColor="#4CAF50"
backgroundColor="#F0F4F8"
secondaryBackgroundColor="#E0E7F0"
textColor="#262730"
font="sans serif"

[server]
port = 8501
maxUploadSize = 50

[deprecation]
showPyplotGlobalUse = false